=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-domain/stagingprosecutors-domain-events/src/main/resources/json/schema/public.prosecutioncasefile.prosecution-submission-succeeded-with-warnings.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://moj.gov.uk/cps/stagingprosecutors/domain/event/public.prosecutioncasefile.prosecution-submission-succeeded-with-warnings.json",
  "type": "object",
  "properties": {
    "caseId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "warnings": {
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/problem.json"
      }
    },
    "caseWarnings": {
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/problem.json"
      }
    },
    "defendantWarnings": {
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/defendant-problem.json"
      }
    },
    "externalId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid",
      "description": "ID originating from the client (SPI or CPPI) for referencing the original message"
    },
    "channel": {
      "type": "string",
      "$ref": "http://cpp.moj.gov.uk/prosecution/casefile/json/schemas/pcf-definitions.json#/definitions/channel"
    }
  },
  "required": [
    "caseId",
    "channel"
  ]
}

=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-integration-test/src/test/resources/importCase/public.prosecutioncasefile.prosecution-submission-succeeded-with-warnings.json
{
  "caseId": "7e2f843e-d639-40b3-8611-8015f3a18958",
  "channel": "CPPI",
  "externalId": "EXTERNAL_ID",
  "warnings": [
    {
      "code": "DEFENDANT_UNDER_18_YEARS_AT_CHARGE_DATE",
      "values": [
        {
          "key": "dateOfBirth",
          "value": "2001-01-01"
        }
      ]
    }
  ]
}
