=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-domain/stagingprosecutors-domain-events/src/main/resources/json/schema/public.stagingprosecutors.cps-serve-bcm-received.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/public.stagingprosecutors.cps-serve-bcm-received.json",
  "type": "object",
  "properties": {
    "prosecutionCaseSubject": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/cps-prosecution-case-subject.json",
      "description": "Identifies the case to which the form is associated to"
    },
    "defendantOffencesSubjects": {
      "description": "Identifies the defendant and offences to which the form is associated to",
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/defendant-offences-subjects.json"
      }
    },
    "tag": {
      "type": "string"
    },
    "evidencePrePTPH": {
      "type": "string"
    },
    "evidencePostPTPH": {
      "type": "string"
    },
    "otherInformation": {
      "type": "string"
    },
    "submissionId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "submissionStatus": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/definitions.json#/definitions/submissionStatus"
    }
  },
  "oneOf": [
    {
      "required": [
        "prosecutionCaseSubject",
        "defendantOffencesSubjects",
        "evidencePrePTPH",
        "submissionId"
      ]
    },
    {
      "required": [
        "prosecutionCaseSubject",
        "defendantOffencesSubjects",
        "evidencePostPTPH",
        "submissionId"
      ]
    },
    {
      "required": [
        "prosecutionCaseSubject",
        "defendantOffencesSubjects",
        "otherInformation",
        "submissionId"
      ]
    }
  ],
  "additionalProperties": true
}

=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-command/stagingprosecutors-command-handler/src/raml/json/example/stagingprosecutors.command.submit-cps-serve-bcm.json
{
  "submissionId": "7e2f843e-d639-40b3-8611-8015f3a18958",
  "prosecutionCaseSubject": {
    "urn": "caseURN",
    "prosecutingAuthority": "The OU Code of the prosecuting authority"
  },
  "defendantOffencesSubjects": [
    {
      "defendant": {
        "prosecutorDefendantId": "defendant Id"
      },
      "offences": [
        {
          "cjsOffenceCode": "offenceCode",
          "offenceDate" : "2021-09-27",
          "offenceWording": "offenceWording"
        }
      ]
    }
  ],
  "evidencePrePTPH": "evidencePrePTPH text"
}
