=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-domain/stagingprosecutors-domain-events/src/main/resources/json/schema/stagingprosecutors.event.prosecution-received.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/prosecution-received.json",
  "type": "object",
  "properties": {
    "submissionId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "submissionStatus": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/definitions.json#/definitions/submissionStatus"
    },
    "prosecutionSubmissionDetails": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/prosecution-submission-details.json"
    },
    "defendants": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/defendant.json"
      }
    }
  },
  "required": [
    "submissionId",
    "submissionStatus",
    "prosecutionSubmissionDetails",
    "defendants"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-command/stagingprosecutors-command-handler/src/test/resources/json/requisition_prosecution_received.json
{
  "defendants": [{
    "defendantDetails": {
      "address": {
        "address1": "Line 1",
        "address2": "Line 2",
        "address3": "Line 3",
        "address4": "Line 4",
        "address5": "Line 5",
        "postcode": "CR0 1XG"
      },
      "documentationLanguage": "E",
      "hearingLanguage": "E",
      "numPreviousConvictions": 3,
      "prosecutorDefendantId": "DVLADEF001"
    },
    "individual": {
      "contactDetails": {
        "homeTelephoneNumber": "1231231230",
        "mobileTelephoneNumber": "1231231230",
        "primaryEmail": "aer@af.com",
        "secondaryEmail": "aer@af.com",
        "workTelephoneNumber": "1231231230"
      },
      "dateOfBirth": "1970-02-03",
      "ethnicity": "W1",
      "gender": 1,
      "languageRequirement": "no special language needs",
      "nameDetails": {
        "forename": "John",
        "forename2": "Adam",
        "forename3": "Theodore",
        "surname": "SMITH",
        "title": "Mr"
      },
      "specificRequirements": "no special needs"
    },
    "offences": [{
      "chargeDate": "2018-06-20",
      "offenceDetails": {
        "backDuty": "+340.30",
        "backDutyDateFrom": "2018-04-30",
        "backDutyDateTo": "2018-05-30",
        "cjsOffenceCode": "CA03010",
        "offenceCommittedDate": "2018-06-20",
        "offenceDateCode": 1,
        "offenceLocation": "Croydon",
        "offenceSequenceNo": 1,
        "offenceWording": "Prosecution charge wording",
        "offenceWordingWelsh": "Prosecution charge wording in Welsh",
        "prosecutorCompensation": "15.30",
        "vehicleMake": "Ford",
        "vehicleRegistrationMark": "AB11 ABC"
      },
      "statementOfFacts": "My statement of facts"
    }]
  }],
  "prosecutionSubmissionDetails": {
    "hearingDetails": {
      "courtHearingLocation": "abcd",
      "dateOfHearing": "1978-02-04",
      "timeOfHearing": "09:05:01.001"
    },
    "informant": "Adam",
    "initiationCode": "Q",
    "prosecutingAuthority": "GAAAA01",
    "urn": "DVLA54321",
    "writtenChargePostingDate": "2015-04-04"
  },
  "submissionId": "8191c165-e9e4-4fd7-ac6d-5bfd04690f77",
  "submissionStatus": "PENDING"
}

=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-command/stagingprosecutors-command-handler/src/test/resources/json/charge_prosecution_received.json
{
  "defendants": [{
    "defendantDetails": {
      "address": {
        "address1": "Line 1",
        "postcode": "CR0 1XG"
      },
      "documentationLanguage": "E",
      "hearingLanguage": "E",
      "numPreviousConvictions": 3,
      "prosecutorDefendantId": "DVLADEF001"
    },
    "individual": {
      "contactDetails": {
        "homeTelephoneNumber": "01212364450",
        "primaryEmail": "aer@gmail.com"
      },
      "custodyStatus": "C",
      "dateOfBirth": "1970-02-03",
      "ethnicity": "W1",
      "gender": 1,
      "nameDetails": {
        "forename": "Alexis",
        "surname": "Sanchez",
        "title": "Mr"
      },
      "observedEthnicity": 1,
      "specificRequirements": "no special needs"
    },
    "offences": [{
      "arrestDate": "2018-07-17",
      "chargeDate": "2018-08-12",
      "offenceDetails": {
        "cjsOffenceCode": "CA03010",
        "offenceCommittedDate": "2018-04-01",
        "offenceDateCode": 1,
        "offenceSequenceNo": 1,
        "offenceWording": "Prosecution charge wording",
        "backDuty": "+340.99",
        "backDutyDateFrom": "2018-04-09",
        "backDutyDateTo": "2018-05-09",
        "vehicleMake": "Ford",
        "vehicleRegistrationMark": "AB11 ABC"
      }
    }]
  }],
  "prosecutionSubmissionDetails": {
    "hearingDetails": {
      "courtHearingLocation": "croydon",
      "dateOfHearing": "2018-08-27",
      "timeOfHearing": "09:05:01.001"
    },
    "initiationCode": "C",
    "prosecutingAuthority": "GAAAA01",
    "urn": "DVLA54321"
  },
  "submissionId": "8191c165-e9e4-4fd7-ac6d-5bfd04690f77",
  "submissionStatus": "PENDING"
}
