=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-command/stagingprosecutors-command-handler/src/raml/json/schema/stagingprosecutors.command.submit-cps-serve-cotr.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/staging/prosecutors/command/handler/submit-cps-serve-cotr.json",
  "type": "object",
  "properties": {
    "submissionId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "prosecutionCaseSubject": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/cps-prosecution-case-subject.json",
      "description": "Identifies the case to which the form is associated to"
    },
    "defendantSubject": {
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/defendant-subject.json"
      },
      "minItems": 1
    },
    "tag": {
      "type": "string"
    },
    "trialDate": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date",
      "description": "The date of the trial"
    },
    "lastRecordedTimeEstimate": {
      "type": "integer",
      "description": "The latest time estimate for the Trial in days (for Crown) or hours (for Mags)"
    },
    "hasAllEvidenceToBeReliedOnBeenServed": {
      "type": "string"
    },
    "hasAllEvidenceToBeReliedOnBeenServedDetails": {
      "type": "string"
    },
    "hasAllDisclosureBeenProvided": {
      "type": "string"
    },
    "hasAllDisclosureBeenProvidedDetails": {
      "type": "string"
    },
    "haveOtherDirectionsBeenCompliedWith": {
      "type": "string"
    },
    "haveOtherDirectionsBeenCompliedWithDetails": {
      "type": "string"
    },
    "haveTheProsecutionWitnessesRequiredToAttendAcknowledgedThatTheyWillAttend": {
      "type": "string"
    },
    "haveTheProsecutionWitnessesRequiredToAttendAcknowledgedThatTheyWillAttendDetails": {
      "type": "string"
    },
    "haveAnyWitnessSummonsesRequiredBeenReceivedAndServed": {
      "type": "string"
    },
    "haveAnyWitnessSummonsesRequiredBeenReceivedAndServedDetails": {
      "type": "string"
    },
    "haveSpecialMeasuresOrRemoteAttendanceIssuesForWitnessesBeenResolved": {
      "type": "string"
    },
    "haveSpecialMeasuresOrRemoteAttendanceIssuesForWitnessesBeenResolvedDetails": {
      "type": "string"
    },
    "haveInterpretersForWitnessesBeenArranged": {
      "type": "string"
    },
    "haveInterpretersForWitnessesBeenArrangedDetails": {
      "type": "string"
    },
    "haveEditedAbeInterviewsBeenPreparedAndAgreed": {
      "type": "string"
    },
    "haveEditedAbeInterviewsBeenPreparedAndAgreedDetails": {
      "type": "string"
    },
    "haveArrangementsBeenMadeForStatementOfPointsOfAgreementAndDisagreement": {
      "type": "string"
    },
    "haveArrangementsBeenMadeForStatementOfPointsOfAgreementAndDisagreementDetails": {
      "type": "string"
    },
    "isTheCaseReadyToProceedWithoutDelayBeforeTheJury": {
      "type": "string"
    },
    "isTheCaseReadyToProceedWithoutDelayBeforeTheJuryDetails": {
      "type": "string"
    },
    "isTheTimeEstimateCorrect": {
      "type": "string"
    },
    "isTheTimeEstimateCorrectDetails": {
      "type": "string"
    },
    "furtherInformationToAssistTheCourt": {
      "type": "string"
    },
    "certifyThatTheProsecutionIsTrialReady": {
      "type": "string"
    },
    "certifyThatTheProsecutionIsTrialReadyDetails": {
      "type": "string"
    },
    "applyForThePtrToBeVacated": {
      "type": "string"
    },
    "applyForThePtrToBeVacatedDetails": {
      "type": "string"
    },
    "formCompletedOnBehalfOfTheProsecutionBy": {
      "type": "string"
    },
    "certificationDate": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date",
      "description": "The certification date"
    }
  },
  "required": [
    "submissionId",
    "prosecutionCaseSubject",
    "defendantSubject",
    "trialDate",
    "hasAllEvidenceToBeReliedOnBeenServed",
    "hasAllDisclosureBeenProvided",
    "haveOtherDirectionsBeenCompliedWith",
    "haveTheProsecutionWitnessesRequiredToAttendAcknowledgedThatTheyWillAttend",
    "haveAnyWitnessSummonsesRequiredBeenReceivedAndServed",
    "haveSpecialMeasuresOrRemoteAttendanceIssuesForWitnessesBeenResolved",
    "haveInterpretersForWitnessesBeenArranged",
    "haveEditedAbeInterviewsBeenPreparedAndAgreed",
    "haveArrangementsBeenMadeForStatementOfPointsOfAgreementAndDisagreement",
    "isTheCaseReadyToProceedWithoutDelayBeforeTheJury",
    "isTheTimeEstimateCorrect",
    "certifyThatTheProsecutionIsTrialReady",
    "applyForThePtrToBeVacated",
    "formCompletedOnBehalfOfTheProsecutionBy",
    "certificationDate"
  ],
  "additionalProperties": true
}

=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-command/stagingprosecutors-command-handler/src/raml/json/example/stagingprosecutors.command.submit-cps-serve-cotr.json
{
  "submissionId": "7e2f843e-d639-40b3-8611-8015f3a18959",
  "prosecutionCaseSubject": {
    "urn": "caseURN",
    "prosecutingAuthority": "The OU Code of the prosecuting authority"
  },
  "defendantSubject": [
    {
      "defendant": {
        "prosecutorDefendantId": "defendant Id"
      }
    }
  ],
  "trialDate": "1980-01-24",
  "lastRecordedTimeEstimate": 14,
  "hasAllEvidenceToBeReliedOnBeenServed": "Y",
  "hasAllEvidenceToBeReliedOnBeenServedDetails": "Details",
  "hasAllDisclosureBeenProvided": "Y",
  "hasAllDisclosureBeenProvidedDetails": "Details",
  "haveOtherDirectionsBeenCompliedWith": "Y",
  "haveOtherDirectionsBeenCompliedWithDetails": "Details",
  "haveTheProsecutionWitnessesRequiredToAttendAcknowledgedThatTheyWillAttend": "Y",
  "haveTheProsecutionWitnessesRequiredToAttendAcknowledgedThatTheyWillAttendDetails": "Details",
  "haveAnyWitnessSummonsesRequiredBeenReceivedAndServed": "Y",
  "haveAnyWitnessSummonsesRequiredBeenReceivedAndServedDetails": "Details",
  "haveSpecialMeasuresOrRemoteAttendanceIssuesForWitnessesBeenResolved": "Y",
  "haveSpecialMeasuresOrRemoteAttendanceIssuesForWitnessesBeenResolvedDetails": "Details",
  "haveInterpretersForWitnessesBeenArranged": "Y",
  "haveInterpretersForWitnessesBeenArrangedDetails": "Details",
  "haveEditedAbeInterviewsBeenPreparedAndAgreed": "Y",
  "haveEditedAbeInterviewsBeenPreparedAndAgreedDetails": "Details",
  "haveArrangementsBeenMadeForStatementOfPointsOfAgreementAndDisagreement": "Y",
  "haveArrangementsBeenMadeForStatementOfPointsOfAgreementAndDisagreementDetails": "Details",
  "isTheCaseReadyToProceedWithoutDelayBeforeTheJury": "Y",
  "isTheCaseReadyToProceedWithoutDelayBeforeTheJuryDetails": "Details",
  "isTheTimeEstimateCorrect": "Y",
  "isTheTimeEstimateCorrectDetails": "Details",
  "furtherInformationToAssistTheCourt": "FurtherInformation",
  "certifyThatTheProsecutionIsTrialReady": "Y",
  "certifyThatTheProsecutionIsTrialReadyDetails": "Details",
  "applyForThePtrToBeVacated": "Y",
  "applyForThePtrToBeVacatedDetails": "Details",
  "formCompletedOnBehalfOfTheProsecutionBy": "FormCompletedBySomeone",
  "certificationDate": "1980-01-24"
}
