=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-event/stagingprosecutors-event-listener/src/yaml/json/schema/stagingprosecutors.event.sjp-prosecution-received.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/sjp-prosecution-received.json",
  "type": "object",
  "properties": {
    "submissionId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "submissionStatus": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/definitions.json#/definitions/submissionStatus"
    },
    "prosecutionSubmissionDetails": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/sjp-prosecution-submission-details.json"
    },
    "defendant": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/sjp-defendant.json",
      "description": ""
    }
  },
  "required": [
    "submissionId",
    "submissionStatus",
    "prosecutionSubmissionDetails",
    "defendant"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-event/stagingprosecutors-event-processor/src/yaml/json/example/stagingprosecutors.event.prosecution-received.json
{
  "submissionId": "8191c165-e9e4-4fd7-ac6d-5bfd04690f77",
  "submissionStatus": "PENDING",
  "prosecutionSubmissionDetails": {
    "prosecutingAuthority": "GAAAA01",
    "initiationCode": "S",
    "urn": "URN500",
    "informant": "Fred",
    "writtenChargePostingDate": "2015-04-04",
    "hearingDetails": {
      "courtHearingLocation" : "abcd",
      "dateOfHearing": "1978-02-04",
      "timeOfHearing": "09:05:01.001"
    }
  },
  "defendant": {
    "prosecutorDefendantId": "123",
    "defendantPerson": {
      "individualDetails": {
        "nameDetails": {
          "title": "Mr",
          "forename": "Joe",
          "surname": "Bloggs"
        },
        "selfDefinedInformation": {
          "gender": 1,
          "ethnicity": "W1"
        }
      }
    },
    "documentationLanguage": "E",
    "prosecutorCosts": "+150.00",
    "hearingLanguage": "E",
    "offences": [
      {
        "cjsOffenceCode": "OFCODE12",
        "offenceSequenceNo": 1,
        "offenceCommittedDate": "2015-04-04",
        "offenceDateCode": 1,
        "offenceWording": "",
        "prosecutorCompensation": "+1.00",
        "backDuty": "200.00",
        "backDutyDateFrom": "2018-04-09",
        "backDutyDateTo": "2018-05-09",
        "vehicleMake": "Ford",
        "vehicleRegistrationMark": "AB11 ABC"
      }
    ]
  }
}

=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-command/stagingprosecutors-command-handler/src/test/resources/json/sjpn_prosecution_received.json
{
  "submissionId": "8191c165-e9e4-4fd7-ac6d-5bfd04690f77",
  "submissionStatus": "PENDING",
  "prosecutionSubmissionDetails": {
    "prosecutingAuthority": "GAAAA01",
    "urn": "URN500",
    "informant": "Fred",
    "writtenChargePostingDate": "2015-04-04"
  },
  "defendant": {
    "prosecutorDefendantId": "123",
    "defendantPerson": {
      "title": "Mr",
      "forename": "Joe",
      "surname": "Bloggs",
      "selfDefinedInformation": {
        "gender": 1,
        "ethnicity": "W1"
      }
    },
    "documentationLanguage": "E",
    "prosecutorCosts": "+150.00",
    "hearingLanguage": "E",
    "offences": [
      {
        "cjsOffenceCode": "OFCODE12",
        "offenceSequenceNo": 1,
        "offenceCommittedDate": "2015-04-04",
        "offenceDateCode": 1,
        "offenceWording": "",
        "prosecutorCompensation": "+1.00",
        "backDuty": "200.00",
        "backDutyDateFrom": "2018-04-09",
        "backDutyDateTo": "2018-05-09",
        "vehicleMake": "Ford",
        "vehicleRegistrationMark": "AB11 ABC"
      }
    ]
  }
}
