=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-common/src/json/schema/stagingprosecutors.cps-ptph-received-details.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://uk.gov.moj.cpp/staging/prosecutors/json/schemas/stagingprosecutors.cps-ptph-received-details.json",
  "type": "object",
  "properties": {
    "submissionId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "submissionStatus": {
      "type": "string",
      "enum": [
        "PENDING",
        "FAILED",
        "REJECTED",
        "SUCCESS",
        "SUCCESS_WITH_WARNINGS",
        "EXPIRED"
      ]
    },
    "prosecutionCaseSubject": {
      "type": "object",
      "properties": {
        "urn": {
          "type": "string",
          "minLength": 1
        },
        "prosecutingAuthority": {
          "type": "string",
          "description": "The OU Code of the prosecuting authority"
        }
      },
      "required": [
        "urn",
        "prosecutingAuthority"
      ],
      "additionalProperties": false
    },
    "cpsDefendant": {
      "description": "Identifies the defendant and offences to which the form is associated to",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "matchingId": {
            "description": "This is randomly generated id for processing only",
            "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
          },
          "prosecutorDefendantId": {
            "description": "A unique reference to a defendant within a prosecution. Provided by the prosecuting authority e.g. DWP",
            "type": "string",
            "maxLength": 36
          },
          "cpsDefendantId": {
            "description": "A unique reference to a defendant within a prosecution. Provided by cps when CPS are prosecuting the case",
            "type": "string",
            "maxLength": 36
          },
          "asn": {
            "description": "A unique reference to a defendant within a prosecution. Provided by the police force and requested from the police by a non police prosecutor e.g. DWP requests from the police",
            "type": "string",
            "maxLength": 21
          },
          "title": {
            "description": "Title by which a defendant is addressed",
            "type": "string"
          },
          "forename": {
            "description": "The first given name of a defendant",
            "type": "string",
            "maxLength": 35
          },
          "forename2": {
            "description": "The second given name of a defendant",
            "type": "string",
            "maxLength": 35
          },
          "forename3": {
            "description": "The third given name of a defendant",
            "type": "string",
            "maxLength": 35
          },
          "surname": {
            "description": "Surname or Family name",
            "type": "string",
            "maxLength": 35
          },
          "dateOfBirth": {
            "description": "The date when the defendant was born",
            "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date"
          },
          "organisationName": {
            "description": "The name of a defendant that is a legal entity",
            "type": "string"
          },
          "parentGuardianForYouthDefendants": {
            "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/defendant-parent-guardian.json"
          },
          "localAuthorityDetailsForYouthDefendants": {
            "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/local-authority-details-for-youth-defendants.json"
          },
          "principalCharges": {
            "type": "string"
          }
        }
      }
    },
    "tag": {
      "type": "string"
    },
    "ptphAdvocate": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/cps-case-contact.json"
    },
    "trialAdvocate": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/cps-case-contact.json"
    },
    "reviewingLawyer": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/cps-case-contact.json"
    },
    "prosecutionCaseProgressionOfficer": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/cps-case-contact.json"
    },
    "officerInTheCase": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/cps-case-contact.json"
    },
    "cpsOffice": {
      "type": "string"
    },
    "draftIndictment": {
      "type": "string"
    },
    "draftIndictmentNotes": {
      "type": "string"
    },
    "summaryOfCircumstances": {
      "type": "string"
    },
    "summaryOfCircumstancesNotes": {
      "type": "string"
    },
    "statementsForPAndICm": {
      "type": "string"
    },
    "statementsForPAndICmNotes": {
      "type": "string"
    },
    "exhibitsForPAndICm": {
      "type": "string"
    },
    "exhibitsForPAndICmNotes": {
      "type": "string"
    },
    "cctv": {
      "type": "string"
    },
    "cctvNotes": {
      "type": "string"
    },
    "streamlinedForensicReport": {
      "type": "string"
    },
    "streamlinedForensicReportNotes": {
      "type": "string"
    },
    "medicalEvidence": {
      "type": "string"
    },
    "medicalEvidenceNotes": {
      "type": "string"
    },
    "expertEvidence": {
      "type": "string"
    },
    "expertEvidenceNotes": {
      "type": "string"
    },
    "badCharacter": {
      "type": "string"
    },
    "badCharacterNotes": {
      "type": "string"
    },
    "hearsay": {
      "type": "string"
    },
    "hearsayNotes": {
      "type": "string"
    },
    "specialMeasures": {
      "type": "string"
    },
    "specialMeasuresNotes": {
      "type": "string"
    },
    "criminalRecord": {
      "type": "string"
    },
    "criminalRecordNotes": {
      "type": "string"
    },
    "victimPersonalStatement": {
      "type": "string"
    },
    "victimPersonalStatementNotes": {
      "type": "string"
    },
    "disclosureManagementDoc": {
      "type": "string"
    },
    "disclosureManagementDocNotes": {
      "type": "string"
    },
    "thirdParty": {
      "type": "string"
    },
    "thirdPartyNotes": {
      "type": "string"
    },
    "reviewDisclosableMaterial": {
      "type": "string"
    },
    "reviewDisclosableMaterialNotes": {
      "type": "string"
    },
    "particularsOfAnyRelatedCriminalProceedings": {
      "type": "string"
    },
    "particularsOfAnyFamily": {
      "type": "string"
    },
    "witnesses": {
      "description": "To provide prosecution witnesses",
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/witness-ptph.json"
      }
    }
  },
  "required": [
    "submissionId",
    "submissionStatus",
    "prosecutionCaseSubject",
    "cpsDefendant",
    "ptphAdvocate",
    "reviewingLawyer",
    "prosecutionCaseProgressionOfficer",
    "officerInTheCase",
    "cpsOffice",
    "draftIndictment",
    "summaryOfCircumstances",
    "statementsForPAndICm",
    "exhibitsForPAndICm",
    "cctv",
    "streamlinedForensicReport",
    "medicalEvidence",
    "expertEvidence",
    "badCharacter",
    "hearsay",
    "specialMeasures",
    "criminalRecord",
    "victimPersonalStatement",
    "disclosureManagementDoc",
    "thirdParty",
    "reviewDisclosableMaterial"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-integration-test/src/test/resources/expected/public.stagingprosecutors.cps-serve-ptph-received.json
{
  "prosecutionCaseSubject": {
    "prosecutingAuthority": "TheOUC",
    "urn": "caseURN"
  },
  "submissionId": "{SUBMISSION_ID}",
  "submissionStatus": "PENDING",
  "cpsDefendant": [
    {
      "cpsDefendantId": "cps-defendant-id",
      "asn": "cps-asn",
      "dateOfBirth": "1990-12-12",
      "forename": "forename",
      "forename2": "forename2",
      "forename3": "forename3",
      "matchingId": "d5ed8708-2b68-4f57-b492-de3df693047a",
      "organisationName": "organisationName",
      "prosecutorDefendantId": "prosecutorDefendantId",
      "surname": "surname",
      "title": "Mr",
      "principalCharges": "principal-charges"
    }
  ],
  "tag": "tag",
  "ptphAdvocate": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "trialAdvocate": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "reviewingLawyer": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "prosecutionCaseProgressionOfficer": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "officerInTheCase": {
    "email": "test@test.com",
    "name": "name",
    "phone": "7778888345"
  },
  "cpsOffice": "CpsOff1",
  "draftIndictment": "Y",
  "draftIndictmentNotes": "Draft Indictment Notes",
  "summaryOfCircumstances": "Y",
  "summaryOfCircumstancesNotes": "Summary Of Circumstances Notes",
  "statementsForPAndICm": "Y",
  "statementsForPAndICmNotes": "Statements For P And ICm Notes",
  "exhibitsForPAndICm": "Y",
  "exhibitsForPAndICmNotes": "Exhibits For P And ICm Notes",
  "cctv": "Y",
  "cctvNotes": "Cctv Notes",
  "streamlinedForensicReport": "Y",
  "streamlinedForensicReportNotes": "Streamlined Forensic Report Notes",
  "medicalEvidence": "Y",
  "medicalEvidenceNotes": "Medical Evidence Notes",
  "expertEvidence": "Y",
  "expertEvidenceNotes": "Expert Evidence Notes",
  "badCharacter": "Y",
  "badCharacterNotes": "Bad Character Notes",
  "hearsay": "Y",
  "hearsayNotes": "Hear say Notes",
  "specialMeasures": "Y",
  "specialMeasuresNotes": "Special Measures Notes",
  "criminalRecord": "Y",
  "criminalRecordNotes": "Criminal Record Notes",
  "victimPersonalStatement": "Y",
  "victimPersonalStatementNotes": "Victim Personal Statement Notes",
  "disclosureManagementDoc": "Y",
  "disclosureManagementDocNotes": "Disclosure Management Doc Notes",
  "thirdParty": "Y",
  "thirdPartyNotes": "Third Party Notes",
  "reviewDisclosableMaterial": "Y",
  "reviewDisclosableMaterialNotes": "Review Disclosable Material Notes",
  "particularsOfAnyFamily": "Particulars Of Any Family",
  "particularsOfAnyRelatedCriminalProceedings": "Particulars Of Any Related Criminal Proceedings",
  "witnesses": [
    {
      "firstNameOfIntermediaryKnownAtPtph": "first name",
      "intermediaryForWitness": "Y",
      "lastNameOfIntermediaryKnownAtPtph": "last name",
      "policeOfficerSubject": {
        "officerInCharge": true,
        "officeCollarNumber": "collar number",
        "officerRank": "Rank1"
      },
      "relevantDisputedIssue": "Issue 1",
      "witnessFirstName": "forename",
      "witnessLastName": "abc"
    }
  ]
}

=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-integration-test/src/test/resources/expected/public.stagingprosecutors.cps-serve-ptph-received-mandatory-fields.json
{
  "prosecutionCaseSubject": {
    "prosecutingAuthority": "TheOUC",
    "urn": "caseURN"
  },
  "submissionId": "{SUBMISSION_ID}",
  "submissionStatus": "PENDING",
  "cpsDefendant": [
    {
      "cpsDefendantId": "cps-defendant-id",
      "matchingId": "d5ed8708-2b68-4f57-b492-de3df693047a",
      "prosecutorDefendantId": "prosecutorDefendantId",
      "principalCharges": "principal-charges"
    }
  ],
  "tag": "tag",
  "ptphAdvocate": {
    "name": "name"
  },
  "reviewingLawyer": {
    "name": "name"
  },
  "prosecutionCaseProgressionOfficer": {
    "name": "name"
  },
  "officerInTheCase": {
    "name": "name"
  },
  "cpsOffice": "CpsOff1",
  "draftIndictment": "Y",
  "summaryOfCircumstances": "Y",
  "statementsForPAndICm": "Y",
  "exhibitsForPAndICm": "Y",
  "cctv": "Y",
  "streamlinedForensicReport": "Y",
  "medicalEvidence": "Y",
  "expertEvidence": "Y",
  "badCharacter": "Y",
  "hearsay": "Y",
  "specialMeasures": "Y",
  "criminalRecord": "Y",
  "victimPersonalStatement": "Y",
  "disclosureManagementDoc": "Y",
  "thirdParty": "Y",
  "reviewDisclosableMaterial": "Y",
  "witnesses": [
    {
      "intermediaryForWitness": "Y",
      "policeOfficerSubject": {
        "officerInCharge": true,
        "officerRank": "Rank1"
      },
      "witnessFirstName": "forename",
      "witnessLastName": "abc"
    }
  ]
}
