=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-command/stagingprosecutors-command-api/src/raml/json/schema/stagingprosecutors.cps-update-cotr.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/staging/prosecutors/command/api/cps-update-cotr.json",
  "type": "object",
  "properties": {
    "cotrSubmissionId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid",
      "description": "Identifier for the CoTR which was returned as part of the creation process"
    },
    "prosecutionCaseSubject": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/cps-prosecution-case-subject.json",
      "description": "Identifies the case to which the form is associated to"
    },
    "defendantSubject": {
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/defendant-subject.json"
      },
      "minItems": 1
    },
    "tag": {
      "type": "string",
      "maxLength": 36
    },
    "furtherProsecutionInformationProvidedAfterCertification": {
      "type": "string",
      "maxLength": 8100
    },
    "trialDate": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date",
      "description": "The date of the trial"
    },
    "certifyThatTheProsecutionIsTrialReady": {
      "type": "string",
      "enum": [
        "Y",
        "N"
      ]
    },
    "formCompletedOnBehalfOfProsecutionBy": {
      "type": "string",
      "maxLength": 1000
    },
    "date": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/date",
      "description": "The certification date"
    }
  },
  "required": [
    "cotrSubmissionId",
    "prosecutionCaseSubject",
    "defendantSubject",
    "furtherProsecutionInformationProvidedAfterCertification",
    "trialDate",
    "certifyThatTheProsecutionIsTrialReady",
    "formCompletedOnBehalfOfProsecutionBy",
    "date"
  ],
  "additionalProperties": true
}

=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-integration-test/src/test/resources/importCase/stagingprosecutors.cps-update-cotr.json
{
  "prosecutionCaseSubject": {
    "urn": "caseURN",
    "prosecutingAuthority": "OU CODE"
  },
  "defendantSubject": [
    {
      "prosecutorDefendantId": "defendant Id",
      "cpsOrganisationDefendantDetails": {
        "organisationName": "orgName",
        "cpsDefendantId": "123"
      },
      "cpsPersonDefendantDetails": {
        "title": "Mr",
        "forename": "foreName",
        "forename2": "TEST",
        "surname": "surname",
        "dateOfBirth": "1990-01-01",
        "localAuthorityDetailsForYouthDefendants": {
          "address1": "address1",
          "authority": "test",
          "email": "test@test.com",
          "forename": "forename",
          "isLookedAfterChild": true,
          "phone": "1234567890",
          "postcode": "G5 0TN",
          "reference": "test",
          "surname": "surname",
          "title": "Mr"
        },
        "parentGuardianForYouthDefendants": {
          "address1": "address1",
          "address2": "address2",
          "email": "test@test.com",
          "forename": "parentForename",
          "phone": "1234567890",
          "postcode": "G5 0TN",
          "relationshipToDefendant": "test",
          "surname": "surname",
          "title": "Mr"
        },
        "cpsDefendantId": "7777"
      },
      "prosecutorPersonDefendantDetails": {
        "title": "Mr",
        "forename": "prosecutorPersonDefendantDetails",
        "forename2": "TEST",
        "forename3": "Test",
        "surname": "test",
        "dateOfBirth": "1990-01-01",
        "localAuthorityDetailsForYouthDefendants": {
          "address1": "address1",
          "authority": "test",
          "email": "test@test.com",
          "forename": "forename",
          "isLookedAfterChild": true,
          "phone": "1234567890",
          "postcode": "G5 0TN",
          "reference": "test",
          "surname": "surname",
          "title": "Mr"
        },
        "parentGuardianForYouthDefendants": {
          "address1": "address1",
          "address2": "address2",
          "email": "test@test.com",
          "forename": "parentForename",
          "phone": "1234567890",
          "postcode": "G5 0TN",
          "relationshipToDefendant": "test",
          "surname": "weterw",
          "title": "Mr"
        },
        "prosecutorDefendantId": "test"
      }
    }
  ],
  "furtherProsecutionInformationProvidedAfterCertification": "Further Prosecution Information Provided After Certification",
  "trialDate": "1980-01-24",
  "certifyThatTheProsecutionIsTrialReady": "Y",
  "formCompletedOnBehalfOfProsecutionBy": "Form Completed On Behalf Of Prosecution By",
  "date": "2022-03-03",
  "cotrSubmissionId": "7e2f843e-d639-40b3-8611-8015f3a18958"
}
