=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-command/stagingprosecutors-command-api/src/raml/json/schema/stagingprosecutors.submit-material-v3.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://uk.gov.moj.cpp/staging/prosecutors/json/schemas/submit-material-v3.json",
  "type": "object",
  "properties": {
    "material": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "materialContentType": {
      "description": "Specifies the format type of the content",
      "type": "string"
    },
    "materialType": {
      "description": "Defines if the material is case level or defendant level",
      "type": "string",
      "maxLength": 40
    },
    "materialName": {
      "description": "The business description of the material contents",
      "type": "string",
      "maxLength": 255
    },
    "fileName": {
      "type": "string",
      "maxLength": 255
    },
    "sectionOrderSequence": {
      "description": "The sequence in which the material is placed within the required section within the case file",
      "type": "integer",
      "maxLength": 6
    },
    "caseSubFolderName": {
      "description": "The name of a subfolder within the relevant section (material type) within the case file in which the material is placed",
      "type": "string",
      "maxLength": 35
    },
    "exhibit": {
      "description": "The details of the exhibit when the material provided is an exibit of evidence",
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/exhibit.json"
    },
    "witnessStatement": {
      "description": "The details of the witness statement when the material provided is statement provided by the investigating authority",
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/witness-statement.json"
    },
    "tag": {
      "description": "A collection of tags that provide further type categorisation and description of the material",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/material-tag.json"
      },
      "uniqueItems": true
    },
    "courtApplicationSubject": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/court-application-subject.json"
    },
    "prosecutionCaseSubject": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/prosecution-case-subject.json"
    }
  },
  "oneOf": [
    {
      "required": [
        "prosecutionCaseSubject"
      ]
    },
    {
      "required": [
        "courtApplicationSubject"
      ]
    }
  ],
  "required": [
    "material",
    "materialContentType",
    "materialType",
    "materialName",
    "fileName"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-command/stagingprosecutors-command-api/src/raml/json/example/stagingprosecutors.event.material-submitted-v3-for-case.json
{
  "material": "2191c165-e9e4-4fd7-ac6d-5bfd04690f77",
  "materialContentType": "text/plain",
  "materialName": "defendant document",
  "materialType": "SJPN",
  "fileName": "Material-File",
  "sectionOrderSequence": 1,
  "caseSubFolderName": "Defendant-Material",
  "exhibit": {
    "reference": "test-reference"
  },
  "witnessStatement": {
    "statementNumber": 2,
    "statementDate": "2021-03-09T14:30:04.881Z"
  },
  "tag": [
    {
      "code": "M35"
    }
  ],
  "prosecutionCaseSubject": {
    "caseUrn" : "CASETFL001",
    "prosecutingAuthority":"00TFL1A",
    "defendantSubject":{
      "prosecutorPersonDefendantDetails":{
        "forename":"David",
        "surname": "Miller",
        "prosecutorDefendantId": "2b9c0dac-deeb-4634-ba69-be5115bdc585",
        "dateOfBirth": "1990-10-23"
      }
    }
  }
}

=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-command/stagingprosecutors-command-api/src/raml/json/example/stagingprosecutors.event.material-submitted-v3-for-court-application.json
{
  "material": "2191c165-e9e4-4fd7-ac6d-5bfd04690f77",
  "materialContentType": "text/plain",
  "materialName": "defendant document",
  "materialType": "SJPN",
  "fileName": "Material-File",
  "sectionOrderSequence": 1,
  "caseSubFolderName": "Defendant-Material",
  "exhibit": {
    "reference": "test-reference"
  },
  "witnessStatement": {
    "statementNumber": 2,
    "statementDate": "2021-03-09T14:30:04.881Z"
  },
  "tag": [
    {
      "code": "M35"
    }
  ],
  "courtApplicationSubject": {
    "courtApplicationId" : "39744949-7a63-4b8a-a564-b94cddda0771"
  }
}
