=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-command/stagingprosecutors-command-api/src/raml/json/schema/stagingprosecutors.cps-serve-ptph-with-submission-id.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/staging/prosecutors/command/api/cps-serve-ptph-with-submission-id.json",
  "type": "object",
  "properties": {
    "submissionId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "prosecutionCaseSubject": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/cps-prosecution-case-subject-ptph.json",
      "description": "Identifies the case to which the form is associated to"
    },
    "defendantOffencesSubjects": {
      "description": "Identifies the defendants to which the PTPH form is associated to with their respective principal charges",
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/defendant-offences-subjects-ptph.json"
      }
    },
    "tag": {
      "type": "string"
    },
    "ptphAdvocate": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/cps-case-contact.json"
    },
    "trialAdvocate": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/cps-case-contact.json"
    },
    "reviewingLawyer": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/cps-case-contact.json"
    },
    "prosecutionCaseProgressionOfficer": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/cps-case-contact.json"
    },
    "officerInTheCase": {
      "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/cps-case-contact.json"
    },
    "cpsOffice": {
      "type": "string"
    },
    "draftIndictment": {
      "type": "string"
    },
    "draftIndictmentNotes": {
      "type": "string"
    },
    "summaryOfCircumstances": {
      "type": "string"
    },
    "summaryOfCircumstancesNotes": {
      "type": "string"
    },
    "statementsForPAndICm": {
      "type": "string"
    },
    "statementsForPAndICmNotes": {
      "type": "string"
    },
    "exhibitsForPAndICm": {
      "type": "string"
    },
    "exhibitsForPAndICmNotes": {
      "type": "string"
    },
    "cctv": {
      "type": "string"
    },
    "cctvNotes": {
      "type": "string"
    },
    "streamlinedForensicReport": {
      "type": "string"
    },
    "streamlinedForensicReportNotes": {
      "type": "string"
    },
    "medicalEvidence": {
      "type": "string"
    },
    "medicalEvidenceNotes": {
      "type": "string"
    },
    "expertEvidence": {
      "type": "string"
    },
    "expertEvidenceNotes": {
      "type": "string"
    },
    "badCharacter": {
      "type": "string"
    },
    "badCharacterNotes": {
      "type": "string"
    },
    "hearsay": {
      "type": "string"
    },
    "hearsayNotes": {
      "type": "string"
    },
    "specialMeasures": {
      "type": "string"
    },
    "specialMeasuresNotes": {
      "type": "string"
    },
    "criminalRecord": {
      "type": "string"
    },
    "criminalRecordNotes": {
      "type": "string"
    },
    "victimPersonalStatement": {
      "type": "string"
    },
    "victimPersonalStatementNotes": {
      "type": "string"
    },
    "disclosureManagementDoc": {
      "type": "string"
    },
    "disclosureManagementDocNotes": {
      "type": "string"
    },
    "thirdParty": {
      "type": "string"
    },
    "thirdPartyNotes": {
      "type": "string"
    },
    "reviewDisclosableMaterial": {
      "type": "string"
    },
    "reviewDisclosableMaterialNotes": {
      "type": "string"
    },
    "particularsOfAnyRelatedCriminalProceedings": {
      "type": "string"
    },
    "particularsOfAnyFamily": {
      "type": "string"
    },
    "witnesses": {
      "description": "To provide prosecution witnesses",
      "type": "array",
      "items": {
        "$ref": "http://cpp.moj.gov.uk/staging/prosecutors/json/schemas/witness-ptph.json"
      }
    }
  },
  "required": [
    "submissionId",
    "prosecutionCaseSubject",
    "defendantOffencesSubjects",
    "ptphAdvocate",
    "reviewingLawyer",
    "prosecutionCaseProgressionOfficer",
    "officerInTheCase",
    "cpsOffice",
    "draftIndictment",
    "summaryOfCircumstances",
    "statementsForPAndICm",
    "exhibitsForPAndICm",
    "cctv",
    "streamlinedForensicReport",
    "medicalEvidence",
    "expertEvidence",
    "badCharacter",
    "hearsay",
    "specialMeasures",
    "criminalRecord",
    "victimPersonalStatement",
    "disclosureManagementDoc",
    "thirdParty",
    "reviewDisclosableMaterial"
  ],
  "additionalProperties": true
}

=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-command/stagingprosecutors-command-handler/src/raml/json/example/stagingprosecutors.command.submit-cps-serve-ptph.json
{
  "submissionId": "7e2f843e-d639-40b3-8611-8015f3a18958",
  "prosecutionCaseSubject": {
    "urn": "caseURN",
    "prosecutingAuthority": "The OU Code of the prosecuting authority"
  },
  "defendantOffencesSubjects": [
    {
      "defendant": {
        "prosecutorDefendantId": "defendant Id"
      },
      "principalCharges": "test"
    }
  ],
  "tag": "tag",
  "ptphAdvocate": {
    "name": "name",
    "phone": "7778888345",
    "email": "test@test.com"
  },
  "trialAdvocate": {
    "name": "name",
    "phone": "7778888345",
    "email": "test@test.com"
  },
  "reviewingLawyer": {
    "name": "name",
    "phone": "7778888345",
    "email": "test@test.com"
  },
  "prosecutionCaseProgressionOfficer": {
    "name": "name",
    "phone": "7778888345",
    "email": "test@test.com"
  },
  "officerInTheCase": {
    "name": "name",
    "phone": "7778888345",
    "email": "test@test.com"
  },
  "cpsOffice": "Cps Office",
  "draftIndictment": "Y",
  "draftIndictmentNotes": "Draft Indictment Notes",
  "summaryOfCircumstances": "Y",
  "summaryOfCircumstancesNotes": "Summary Of Circumstances Notes",
  "statementsForPAndICm": "Y",
  "statementsForPAndICmNotes": "Statements For P And ICm Notes",
  "exhibitsForPAndICm": "Y",
  "exhibitsForPAndICmNotes": "Exhibits For P And ICm Notes",
  "cctv": "Y",
  "cctvNotes": "Cctv Notes",
  "streamlinedForensicReport": "Y",
  "streamlinedForensicReportNotes": "Streamlined Forensic Report Notes",
  "medicalEvidence": "Y",
  "medicalEvidenceNotes": "Medical Evidence Notes",
  "expertEvidence": "Y",
  "badCharacter": "Y",
  "badCharacterNotes": "Bad Character Notes",
  "hearsay": "Y",
  "hearsayNotes": "Hear say Notes",
  "specialMeasures": "Y",
  "specialMeasuresNotes": "Special Measures Notes",
  "criminalRecord": "Y",
  "criminalRecordNotes": "Criminal Record Notes",
  "victimPersonalStatement": "Y",
  "victimPersonalStatementNotes": "Victim Personal Statement Notes",
  "disclosureManagementDoc": "Y",
  "disclosureManagementDocNotes": "Disclosure Management Doc Notes",
  "thirdParty": "Y",
  "thirdPartyNotes": "Third Party Notes",
  "reviewDisclosableMaterial": "Y",
  "reviewDisclosableMaterialNotes": "Review Disclosable Material Notes",
  "particularsOfAnyRelatedCriminalProceedings": "Particulars Of Any Related Criminal Proceedings",
  "particularsOfAnyFamily": "Particulars Of Any Family",
  "witnesses": [
    {
      "witnessFirstName": "forename",
      "witnessLastName": "abc",
      "relevantDisputedIssue": "Issue 1",
      "intermediaryForWitness": "Y",
      "firstNameOfIntermediaryKnownAtPtph": "first name",
      "lastNameOfIntermediaryKnownAtPtph": "last name",
      "policeOfficerSubject": {
        "officerInCharge": true,
        "officerRank": "Rank1"
      }
    }
  ]
}

=== hmcts/cpp-context-staging-prosecutors/stagingprosecutors-command/stagingprosecutors-command-handler/src/test/resources/json/cps-serve-ptph.json
{
  "submissionId": "7e2f843e-d639-40b3-8611-8015f3a18958",
  "prosecutionCaseSubject": {
    "urn": "caseURN",
    "prosecutingAuthority": "The OU Code of the prosecuting authority"
  },
  "defendantOffencesSubjects": [
    {
      "defendant": {
        "prosecutorDefendantId": "defendant Id"
      },
      "principalCharges": "test"
    }
  ],
  "tag": "tag",
  "ptphAdvocate": {
    "email": "Email",
    "name": "name",
    "phone": "phone number"
  },
  "trialAdvocate": {
    "email": "Email",
    "name": "name",
    "phone": "phone number"
  },
  "reviewingLawyer": {
    "email": "Email",
    "name": "name",
    "phone": "phone number"
  },
  "prosecutionCaseProgressionOfficer": {
    "email": "Email",
    "name": "name",
    "phone": "phone number"
  },
  "officerInTheCase": {
    "email": "Email",
    "name": "name",
    "phone": "phone number"
  },
  "cpsOffice": "Cps Office",
  "draftIndictment": "Draft Indictment",
  "draftIndictmentNotes": "Draft Indictment Notes",
  "summaryOfCircumstances": "Summary Of Circumstances",
  "summaryOfCircumstancesNotes": "Summary Of Circumstances Notes",
  "statementsForPAndICm": "Statements For P And ICm",
  "statementsForPAndICmNotes": "Statements For P And ICm Notes",
  "exhibitsForPAndICm": "Exhibits For P And ICm",
  "exhibitsForPAndICmNotes": "Exhibits For P And ICm Notes",
  "cctv": "Cctv",
  "cctvNotes": "Cctv Notes",
  "streamlinedForensicReport": "Streamlined Forensic Report",
  "streamlinedForensicReportNotes": "Streamlined Forensic Report Notes",
  "medicalEvidence": "Medical Evidence",
  "medicalEvidenceNotes": "Medical Evidence Notes",
  "expertEvidence": "Expert Evidence",
  "badCharacter": "Bad Character",
  "badCharacterNotes": "Bad Character Notes",
  "hearsay": "Hear say",
  "hearsayNotes": "Hear say Notes",
  "specialMeasures": "Special Measures",
  "specialMeasuresNotes": "Special Measures Notes",
  "criminalRecord": "Criminal Record",
  "criminalRecordNotes": "Criminal Record Notes",
  "victimPersonalStatement": "Victim Personal Statement",
  "victimPersonalStatementNotes": "Victim Personal Statement Notes",
  "disclosureManagementDoc": "Disclosure Management Doc",
  "disclosureManagementDocNotes": "Disclosure Management Doc Notes",
  "thirdParty": "Third Party",
  "thirdPartyNotes": "Third Party Notes",
  "reviewDisclosableMaterial": "Review Disclosable Material",
  "reviewDisclosableMaterialNotes": "Review Disclosable Material Notes",
  "particularsOfAnyRelatedCriminalProceedings": "Particulars Of Any Related Criminal Proceedings",
  "particularsOfAnyFamily": "Particulars Of Any Family",
  "witnesses": [
    {
      "witnessFirstName": "forename",
      "witnessLastName": "abc",
      "relevantDisputedIssue": "Issue 1",
      "intermediaryForWitness": "Y",
      "firstNameOfIntermediaryKnownAtPtph": "first name",
      "lastNameOfIntermediaryKnownAtPtph": "last name",
      "policeOfficerSubject": {
        "officerInCharge": true,
        "officerRank": "Rank1"
      }
    }
  ]
}
